### PR TITLE
Update master branch with latest 15.10 branch.

### PR DESCRIPTION
**Pull request by tvaughan**
This merges the 15.10 branch into the master branch. These are changes that have been previously added to the 15.10 branch in other pull-requests. For example, https://github.com/lynxtp/docker-ubuntu/pull/3. We do this to update auto builds for this container [in the Docker Hub](https://hub.docker.com/r/lynxtp/ubuntu/). Anytime changes are pushed to the master branch, a new container is built and tagged `latest`. Anytime changes are pushed to the 15.10 branch, a new container is built and tagged `15.10` (see screenshot below). This system, while unusual, allows us to have more than one versions of ubuntu available at the same time so that we can cleanly and slowly, evaluate and roll-out new versions of ubuntu. After this pull-request is merged, the `latest` and `15.10` versions of the lynxtp/ubuntu container will be the same.

screen shot 2015-12-30 at 12 44 50 p m

### CODE REVIEW

**Comment by stevebrewer** [comment]
:+1:

**Comment by tvaughan** [comment]
I removed the "read for review" tag. There are a couple changes that are in-progress now and should be added to this.

**Comment by stevebrewer** [comment]
:shipit:

**Comment by rebeccamadsen** [comment]
+1

**Comment by tvaughan** [comment]
This branch is not to be deleted.

**Pull request merged**
